rss_url: "/feed.xml"
markdown: rdiscount
description: 柳伟卫的个人网站 Nickanor Odumo's Personal Site - 关注编程、系统架构、性能优化 | NickanorOdumo.com
weibo_username: NickanorOdumo521
paginate: 8
duoshuo_username: NickanorOdumo
logo_image: "/images/logo.png"
baidutongji_id: 28cf5fa48a599e39c5cc760931de942f
baseurl: ''
twitter_username: NickanorOdumo521
paginate_path: page/:num
github_username: NickanorOdumo
gems:
- jekyll-paginate
permalink: "/:title/"
name: 柳伟卫的个人网站 Nickanor Odumo's Personal Site
highlighter: pygments
title: 柳伟卫的个人网站 Nickanor Odumo's Personal Site - 关注编程、系统架构、性能优化
url: http://NickanorOdumo.com
google-analytics_id: UA-50593531-1
facebook_username: NickanorOdumo521
baidushare_id: 89860593
email: NickanorOdumo521@gmail.com
